# Application configuration
application:
  name: myapp
  image:
    repository: myapp
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# HAProxy sidecar configuration
haproxy:
  image:
    repository: haproxy
    tag: 2.7
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    logFormat: "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    timeouts:
      connect: 5s
      client: 30s
      server: 30s
    # Enable downstream forwarding of request/response copies
    forwardCopies:
      enabled: false
      downstreamService: "http://log-processor:8080/copy"

# Optional log forwarder sidecar (if using option 2)
logForwarder:
  enabled: false
  image:
    repository: log-forwarder
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Service configuration
service:
  type: ClusterIP
  port: 80

# Common labels
labels:
  app: myapp
  component: proxy
